// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ingestion.Data;

#nullable disable

namespace ingestion.Migrations
{
    [DbContext(typeof(IngestionDbContext))]
    partial class IngestionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("knowledge")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ingestion.Entities.CrawlJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<int>("DocsFound")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("docs_found");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("RUNNING")
                        .HasColumnName("status");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger_type");

                    b.Property<Guid?>("TriggeredBy")
                        .HasColumnType("uuid")
                        .HasColumnName("triggered_by");

                    b.HasKey("Id");

                    b.HasIndex("TriggeredBy");

                    b.ToTable("crawl_job", "knowledge");
                });

            modelBuilder.Entity("ingestion.Entities.KbChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Article")
                        .HasColumnType("text")
                        .HasColumnName("article");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer")
                        .HasColumnName("chunk_index");

                    b.Property<string>("Clause")
                        .HasColumnType("text")
                        .HasColumnName("clause");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<Guid>("KnowledgeDocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("knowledge_document_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<int?>("Page")
                        .HasColumnType("integer")
                        .HasColumnName("page");

                    b.Property<string>("Point")
                        .HasColumnType("text")
                        .HasColumnName("point");

                    b.Property<string>("QdrantPointId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qdrant_point_id");

                    b.HasKey("Id");

                    b.HasIndex("QdrantPointId")
                        .IsUnique();

                    b.HasIndex("KnowledgeDocumentId", "ChunkIndex")
                        .IsUnique();

                    b.ToTable("kb_chunk", "knowledge");
                });

            modelBuilder.Entity("ingestion.Entities.KnowledgeDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("ContentJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("content_json");

                    b.Property<Guid?>("CrawlJobId")
                        .HasColumnType("uuid")
                        .HasColumnName("crawl_job_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("EffectiveFrom")
                        .HasColumnType("date")
                        .HasColumnName("effective_from");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date")
                        .HasColumnName("effective_to");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_hash");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("indexed_at");

                    b.Property<DateOnly?>("IssuedDate")
                        .HasColumnType("date")
                        .HasColumnName("issued_date");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<Guid>("LegalSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("legal_source_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("CrawlJobId");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.HasIndex("UploadedBy");

                    b.HasIndex("LegalSourceId", "VersionNo")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_knowledge_document_4");

                    b.ToTable("knowledge_document", "knowledge");
                });

            modelBuilder.Entity("ingestion.Entities.LegalAmendment", b =>
                {
                    b.Property<Guid>("AmendingSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("amending_source_id");

                    b.Property<Guid>("AmendedSourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("amended_source_id");

                    b.Property<string>("AffectedArticles")
                        .HasColumnType("jsonb")
                        .HasColumnName("affected_articles");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RelationType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("AMENDS")
                        .HasColumnName("relation_type");

                    b.HasKey("AmendingSourceId", "AmendedSourceId");

                    b.HasIndex("AmendedSourceId");

                    b.ToTable("legal_amendment", "knowledge");
                });

            modelBuilder.Entity("ingestion.Entities.LegalSource", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DocType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("doc_type");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("document_number");

                    b.Property<string>("IssuingAuthority")
                        .HasColumnType("text")
                        .HasColumnName("issuing_authority");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.HasIndex("DocumentNumber")
                        .IsUnique();

                    b.ToTable("legal_source", "knowledge");
                });

            modelBuilder.Entity("ingestion.Entities.Stubs.UserStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("users", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("ingestion.Entities.CrawlJob", b =>
                {
                    b.HasOne("ingestion.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("TriggeredBy")
                        .HasConstraintName("fk_crawl_job_23");
                });

            modelBuilder.Entity("ingestion.Entities.KbChunk", b =>
                {
                    b.HasOne("ingestion.Entities.KnowledgeDocument", "KnowledgeDocument")
                        .WithMany("Chunks")
                        .HasForeignKey("KnowledgeDocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kb_chunk_22");

                    b.Navigation("KnowledgeDocument");
                });

            modelBuilder.Entity("ingestion.Entities.KnowledgeDocument", b =>
                {
                    b.HasOne("ingestion.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("fk_knowledge_document_21");

                    b.HasOne("ingestion.Entities.CrawlJob", "CrawlJob")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("CrawlJobId")
                        .HasConstraintName("fk_knowledge_document_19");

                    b.HasOne("ingestion.Entities.LegalSource", "LegalSource")
                        .WithMany("KnowledgeDocuments")
                        .HasForeignKey("LegalSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_knowledge_document_18");

                    b.HasOne("ingestion.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .HasConstraintName("fk_knowledge_document_20");

                    b.Navigation("CrawlJob");

                    b.Navigation("LegalSource");
                });

            modelBuilder.Entity("ingestion.Entities.LegalAmendment", b =>
                {
                    b.HasOne("ingestion.Entities.LegalSource", "AmendedSource")
                        .WithMany("AmendedAmendments")
                        .HasForeignKey("AmendedSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_amendment_17");

                    b.HasOne("ingestion.Entities.LegalSource", "AmendingSource")
                        .WithMany("AmendingAmendments")
                        .HasForeignKey("AmendingSourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_legal_amendment_16");

                    b.Navigation("AmendedSource");

                    b.Navigation("AmendingSource");
                });

            modelBuilder.Entity("ingestion.Entities.CrawlJob", b =>
                {
                    b.Navigation("KnowledgeDocuments");
                });

            modelBuilder.Entity("ingestion.Entities.KnowledgeDocument", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("ingestion.Entities.LegalSource", b =>
                {
                    b.Navigation("AmendedAmendments");

                    b.Navigation("AmendingAmendments");

                    b.Navigation("KnowledgeDocuments");
                });
#pragma warning restore 612, 618
        }
    }
}
