export const draftSteps = [
  'Choose template',
  'Working input',
  'Confirm snapshot',
  'Create draft',
  'Preview & actions',
] as const
export const draftScenarios = [
  'ready',
  'empty',
  'warnings',
  'blocked-reviewable',
  'blocked-service',
  'validation-failed',
  'grounding-missing',
  'generating',
  'generation-failed',
  'network-error',
  'version-history',
  'template-unavailable',
  'stale-input',
  'chat-suggestion',
  'no-chat-context',
  'confirm-then-job-fails',
  'save-failed',
  'required-agency-missing',
  'history-same-snapshot',
  'history-empty',
  'version-unavailable',
  'generation-timeout-unknown',
  'retry-success',
  'template-inactive',
  'template-no-changelog',
  'export-success',
  'export-failed',
  'export-insufficient-credit',
  'export-quote-expired',
  'export-timeout-unknown',
  'artifact-download-failed',
  'assessment-pending',
  'assessment-failed',
  'revise-cancel',
  'revise-success',
  'save-conflict',
  'snapshot-detail',
  'source-unavailable',
  'handoff-success',
  'handoff-failed',
  'handoff-blocked',
  'resume-job',
  'unauthorized',
  'forbidden',
] as const
export const draftDisclaimer =
  'AI-assisted draft — not professionally verified. Readiness is not expert approval. Check the input, sources and applicable rules before use.'
