// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using billing.Data;

#nullable disable

namespace billing.Migrations
{
    [DbContext(typeof(BillingDbContext))]
    [Migration("20261004092741_InitialBilling")]
    partial class InitialBilling
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("billing")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("billing.Entities.BankAccount", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AccountHolderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_holder_name");

                    b.Property<string>("AccountLast4")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_last4");

                    b.Property<string>("AccountNumberEnc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number_enc");

                    b.Property<string>("AccountNumberHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("account_number_hash");

                    b.Property<string>("BankBin")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_bin");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_default");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("text")
                        .HasColumnName("rejection_reason");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("UNVERIFIED")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset?>("VerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("verified_at");

                    b.Property<Guid?>("VerifiedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("VerifiedBy");

                    b.ToTable("bank_account", "billing");
                });

            modelBuilder.Entity("billing.Entities.CreditLedger", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EntryType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entry_type");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid?>("RefAiUsageId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_ai_usage_id");

                    b.Property<Guid?>("RefDocumentVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_document_version_id");

                    b.Property<Guid?>("RefPaymentId")
                        .HasColumnType("uuid")
                        .HasColumnName("ref_payment_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RefPaymentId");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_credit_ledger_2");

                    b.ToTable("credit_ledger", "billing");
                });

            modelBuilder.Entity("billing.Entities.CreditWallet", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<long>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("balance");

                    b.Property<long>("Held")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("held");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.ToTable("credit_wallet", "billing");
                });

            modelBuilder.Entity("billing.Entities.Dispute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArbiterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("arbiter_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Evidence")
                        .HasColumnType("jsonb")
                        .HasColumnName("evidence");

                    b.Property<string>("Grounds")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grounds");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<Guid>("RaisedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("raised_by");

                    b.Property<string>("ResolutionNote")
                        .HasColumnType("text")
                        .HasColumnName("resolution_note");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<DateTimeOffset>("SlaDueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sla_due_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ArbiterUserId");

                    b.HasIndex("RaisedBy");

                    b.HasIndex("ReviewCaseId")
                        .IsUnique();

                    b.ToTable("dispute", "billing");
                });

            modelBuilder.Entity("billing.Entities.Escrow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("HELD")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ReviewCaseId")
                        .IsUnique();

                    b.ToTable("escrow", "billing");
                });

            modelBuilder.Entity("billing.Entities.PaymentTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("order_code");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PAYOS")
                        .HasColumnName("provider");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<Guid?>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("ReviewCaseId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("ix_payment_transaction_2");

                    b.ToTable("payment_transaction", "billing");
                });

            modelBuilder.Entity("billing.Entities.PayoutTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<Guid?>("BankAccountId")
                        .HasColumnType("uuid")
                        .HasColumnName("bank_account_id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("LastError")
                        .HasColumnType("text")
                        .HasColumnName("last_error");

                    b.Property<string>("PayoutType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payout_type");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PAYOS")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderRef")
                        .HasColumnType("text")
                        .HasColumnName("provider_ref");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("recipient_user_id");

                    b.Property<Guid>("SettlementId")
                        .HasColumnType("uuid")
                        .HasColumnName("settlement_id");

                    b.Property<string>("SnapAccountLast4")
                        .HasColumnType("text")
                        .HasColumnName("snap_account_last4");

                    b.Property<string>("SnapBankBin")
                        .HasColumnType("text")
                        .HasColumnName("snap_bank_bin");

                    b.Property<string>("SnapBankName")
                        .HasColumnType("text")
                        .HasColumnName("snap_bank_name");

                    b.Property<string>("SnapHolderName")
                        .HasColumnType("text")
                        .HasColumnName("snap_holder_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("BankAccountId");

                    b.HasIndex("ProviderRef")
                        .IsUnique();

                    b.HasIndex("RecipientUserId");

                    b.HasIndex("SettlementId", "PayoutType")
                        .IsUnique();

                    b.HasIndex("Status", "CreatedAt")
                        .HasDatabaseName("ix_payout_transaction_4");

                    b.ToTable("payout_transaction", "billing");
                });

            modelBuilder.Entity("billing.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("ExpertPayoutAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("expert_payout_amount");

                    b.Property<long>("PlatformFeeAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("platform_fee_amount");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<DateTimeOffset>("SettledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("UserRefundAmount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("user_refund_amount");

                    b.HasKey("Id");

                    b.HasIndex("ReviewCaseId")
                        .IsUnique();

                    b.ToTable("settlement", "billing");
                });

            modelBuilder.Entity("billing.Entities.Stubs.ReviewCaseStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("review_case", "review", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("billing.Entities.Stubs.UserStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("users", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("billing.Entities.BankAccount", b =>
                {
                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_bank_account_58");

                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("VerifiedBy")
                        .HasConstraintName("fk_bank_account_59");
                });

            modelBuilder.Entity("billing.Entities.CreditLedger", b =>
                {
                    b.HasOne("billing.Entities.PaymentTransaction", "PaymentTransaction")
                        .WithMany()
                        .HasForeignKey("RefPaymentId")
                        .HasConstraintName("fk_credit_ledger_70");

                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_ledger_69");

                    b.Navigation("PaymentTransaction");
                });

            modelBuilder.Entity("billing.Entities.CreditWallet", b =>
                {
                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_credit_wallet_68");
                });

            modelBuilder.Entity("billing.Entities.Dispute", b =>
                {
                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("ArbiterUserId")
                        .HasConstraintName("fk_dispute_65");

                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("RaisedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_64");

                    b.HasOne("billing.Entities.Stubs.ReviewCaseStub", null)
                        .WithOne()
                        .HasForeignKey("billing.Entities.Dispute", "ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dispute_63");
                });

            modelBuilder.Entity("billing.Entities.Escrow", b =>
                {
                    b.HasOne("billing.Entities.Stubs.ReviewCaseStub", null)
                        .WithOne()
                        .HasForeignKey("billing.Entities.Escrow", "ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_escrow_56");
                });

            modelBuilder.Entity("billing.Entities.PaymentTransaction", b =>
                {
                    b.HasOne("billing.Entities.Stubs.ReviewCaseStub", null)
                        .WithMany()
                        .HasForeignKey("ReviewCaseId")
                        .HasConstraintName("fk_payment_transaction_67");

                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_transaction_66");
                });

            modelBuilder.Entity("billing.Entities.PayoutTransaction", b =>
                {
                    b.HasOne("billing.Entities.BankAccount", "BankAccount")
                        .WithMany()
                        .HasForeignKey("BankAccountId")
                        .HasConstraintName("fk_payout_transaction_61");

                    b.HasOne("billing.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payout_transaction_62");

                    b.HasOne("billing.Entities.Settlement", "Settlement")
                        .WithMany("PayoutTransactions")
                        .HasForeignKey("SettlementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payout_transaction_60");

                    b.Navigation("BankAccount");

                    b.Navigation("Settlement");
                });

            modelBuilder.Entity("billing.Entities.Settlement", b =>
                {
                    b.HasOne("billing.Entities.Stubs.ReviewCaseStub", null)
                        .WithOne()
                        .HasForeignKey("billing.Entities.Settlement", "ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_settlement_57");
                });

            modelBuilder.Entity("billing.Entities.Settlement", b =>
                {
                    b.Navigation("PayoutTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
