// <auto-generated />
using System;
using System.Net;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using auth.Data;

#nullable disable

namespace auth.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20261008074813_AuthPermissions")]
    partial class AuthPermissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("identity")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("auth.Entities.AuthEmailOutbox", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SentAt");

                    b.ToTable("auth_email_outbox", "identity");
                });

            modelBuilder.Entity("auth.Entities.AuthRefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<IPAddress>("IpAddress")
                        .HasColumnType("inet")
                        .HasColumnName("ip_address");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.Property<Guid?>("RotatedFrom")
                        .HasColumnType("uuid")
                        .HasColumnName("rotated_from");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("RotatedFrom");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId", "ExpiresAt")
                        .HasDatabaseName("ix_auth_refresh_token_2");

                    b.ToTable("auth_refresh_token", "identity");
                });

            modelBuilder.Entity("auth.Entities.AvailabilitySlot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("EndAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_at");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<DateTimeOffset>("StartAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ExpertProfileId", "Status", "StartAt")
                        .HasDatabaseName("ix_availability_slot_2");

                    b.ToTable("availability_slot", "identity");
                });

            modelBuilder.Entity("auth.Entities.BusinessProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("company_name");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Representative")
                        .HasColumnType("text")
                        .HasColumnName("representative");

                    b.Property<string>("TaxCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tax_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("business_profile", "identity");
                });

            modelBuilder.Entity("auth.Entities.ExpertCompetencyAssessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssessorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("assessor_user_id");

                    b.Property<short>("C1Score")
                        .HasColumnType("smallint")
                        .HasColumnName("c1_score");

                    b.Property<short>("C2Score")
                        .HasColumnType("smallint")
                        .HasColumnName("c2_score");

                    b.Property<short>("C3Score")
                        .HasColumnType("smallint")
                        .HasColumnName("c3_score");

                    b.Property<short>("C4Score")
                        .HasColumnType("smallint")
                        .HasColumnName("c4_score");

                    b.Property<short>("C5Score")
                        .HasColumnType("smallint")
                        .HasColumnName("c5_score");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("decision");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("Rationale")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rationale");

                    b.HasKey("Id");

                    b.HasIndex("AssessorUserId");

                    b.HasIndex("ExpertProfileId")
                        .HasDatabaseName("ix_expert_competency_assessment_2");

                    b.ToTable("expert_competency_assessment", "identity");
                });

            modelBuilder.Entity("auth.Entities.ExpertEvidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EvidenceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evidence_type");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<string>("ParsedMeta")
                        .HasColumnType("jsonb")
                        .HasColumnName("parsed_meta");

                    b.Property<string>("ScreeningFlag")
                        .HasColumnType("text")
                        .HasColumnName("screening_flag");

                    b.HasKey("Id");

                    b.HasIndex("ExpertProfileId")
                        .HasDatabaseName("ix_expert_evidence_2");

                    b.ToTable("expert_evidence", "identity");
                });

            modelBuilder.Entity("auth.Entities.ExpertProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<Guid?>("ApprovedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("approved_by");

                    b.Property<string>("Bio")
                        .HasColumnType("text")
                        .HasColumnName("bio");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EligibilityNote")
                        .HasColumnType("text")
                        .HasColumnName("eligibility_note");

                    b.Property<decimal>("RatingAvg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("rating_avg");

                    b.Property<int>("RatingCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("rating_count");

                    b.Property<string>("ServiceStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("INACTIVE")
                        .HasColumnName("service_status");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("SCREENING")
                        .HasColumnName("status");

                    b.Property<int?>("TurnaroundHours")
                        .HasColumnType("integer")
                        .HasColumnName("turnaround_hours");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int?>("YearsExperience")
                        .HasColumnType("integer")
                        .HasColumnName("years_experience");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedBy");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex("Status", "ServiceStatus")
                        .HasDatabaseName("ix_expert_marketplace_feed");

                    b.ToTable("expert_profile", "identity");
                });

            modelBuilder.Entity("auth.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("permission", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Code = "profile:read",
                            Description = "profile:read"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Code = "profile:write",
                            Description = "profile:write"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Code = "business:read",
                            Description = "business:read"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Code = "business:write",
                            Description = "business:write"
                        });
                });

            modelBuilder.Entity("auth.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("roles", "identity");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Code = "USER",
                            Name = "USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Code = "EXPERT",
                            Name = "EXPERT"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Code = "AUTHOR_REVIEWER",
                            Name = "AUTHOR_REVIEWER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Code = "KNOWLEDGE_ADMIN",
                            Name = "KNOWLEDGE_ADMIN"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            Code = "SYSTEM_ADMIN",
                            Name = "SYSTEM_ADMIN"
                        });
                });

            modelBuilder.Entity("auth.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permission", "identity");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("10000000-0000-0000-0000-000000000001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        });
                });

            modelBuilder.Entity("auth.Entities.ServiceOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<long>("Fee")
                        .HasColumnType("bigint")
                        .HasColumnName("fee");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_type");

                    b.HasKey("Id");

                    b.HasIndex("ExpertProfileId", "IsActive")
                        .HasDatabaseName("ix_service_offering_2");

                    b.ToTable("service_offering", "identity");
                });

            modelBuilder.Entity("auth.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("EmailVerifiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("email_verified_at");

                    b.Property<int>("FailedLoginAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("failed_login_attempts");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING_VERIFICATION")
                        .HasColumnName("status");

                    b.Property<int>("TokenVersion")
                        .HasColumnType("integer")
                        .HasColumnName("token_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("users", "identity");
                });

            modelBuilder.Entity("auth.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "identity");
                });

            modelBuilder.Entity("auth.Entities.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTimeOffset?>("InvalidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invalidated_at");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("purpose");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("token_hash");

                    b.Property<DateTimeOffset?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("verification_token", "identity");
                });

            modelBuilder.Entity("auth.Entities.AuthRefreshToken", b =>
                {
                    b.HasOne("auth.Entities.AuthRefreshToken", "RotatedFromToken")
                        .WithMany("RotatedToTokens")
                        .HasForeignKey("RotatedFrom")
                        .HasConstraintName("fk_auth_refresh_token_6");

                    b.HasOne("auth.Entities.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_auth_refresh_token_5");

                    b.Navigation("RotatedFromToken");

                    b.Navigation("User");
                });

            modelBuilder.Entity("auth.Entities.AvailabilitySlot", b =>
                {
                    b.HasOne("auth.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("AvailabilitySlots")
                        .HasForeignKey("ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_availability_slot_15");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("auth.Entities.BusinessProfile", b =>
                {
                    b.HasOne("auth.Entities.User", "User")
                        .WithOne("BusinessProfile")
                        .HasForeignKey("auth.Entities.BusinessProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_business_profile_8");

                    b.Navigation("User");
                });

            modelBuilder.Entity("auth.Entities.ExpertCompetencyAssessment", b =>
                {
                    b.HasOne("auth.Entities.User", "Assessor")
                        .WithMany()
                        .HasForeignKey("AssessorUserId")
                        .IsRequired()
                        .HasConstraintName("fk_expert_competency_assessment_13");

                    b.HasOne("auth.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("Assessments")
                        .HasForeignKey("ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_expert_competency_assessment_12");

                    b.Navigation("Assessor");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("auth.Entities.ExpertEvidence", b =>
                {
                    b.HasOne("auth.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("Evidences")
                        .HasForeignKey("ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_expert_evidence_11");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("auth.Entities.ExpertProfile", b =>
                {
                    b.HasOne("auth.Entities.User", "Approver")
                        .WithMany()
                        .HasForeignKey("ApprovedBy")
                        .HasConstraintName("fk_expert_profile_10");

                    b.HasOne("auth.Entities.User", "User")
                        .WithOne("ExpertProfile")
                        .HasForeignKey("auth.Entities.ExpertProfile", "UserId")
                        .IsRequired()
                        .HasConstraintName("fk_expert_profile_9");

                    b.Navigation("Approver");

                    b.Navigation("User");
                });

            modelBuilder.Entity("auth.Entities.RolePermission", b =>
                {
                    b.HasOne("auth.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_4");

                    b.HasOne("auth.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permission_3");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("auth.Entities.ServiceOffering", b =>
                {
                    b.HasOne("auth.Entities.ExpertProfile", "ExpertProfile")
                        .WithMany("ServiceOfferings")
                        .HasForeignKey("ExpertProfileId")
                        .IsRequired()
                        .HasConstraintName("fk_service_offering_14");

                    b.Navigation("ExpertProfile");
                });

            modelBuilder.Entity("auth.Entities.UserRole", b =>
                {
                    b.HasOne("auth.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_2");

                    b.HasOne("auth.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_roles_1");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("auth.Entities.VerificationToken", b =>
                {
                    b.HasOne("auth.Entities.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_verification_token_7");

                    b.Navigation("User");
                });

            modelBuilder.Entity("auth.Entities.AuthRefreshToken", b =>
                {
                    b.Navigation("RotatedToTokens");
                });

            modelBuilder.Entity("auth.Entities.ExpertProfile", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("AvailabilitySlots");

                    b.Navigation("Evidences");

                    b.Navigation("ServiceOfferings");
                });

            modelBuilder.Entity("auth.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("auth.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("auth.Entities.User", b =>
                {
                    b.Navigation("BusinessProfile");

                    b.Navigation("ExpertProfile");

                    b.Navigation("RefreshTokens");

                    b.Navigation("UserRoles");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
