<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="FluentValidation.AspNetCore" />
    <ProjectReference Include="..\abstractions\abstractions.csproj" />
    <ProjectReference Include="..\exceptions\exceptions.csproj" />
    <ProjectReference Include="..\wrappers\wrappers.csproj" />
    <ProjectReference Include="..\security\security.csproj" />
    <ProjectReference Include="..\messaging\messaging.csproj" />
  </ItemGroup>

</Project>
