// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using workflow.Data;

#nullable disable

namespace workflow.Migrations
{
    [DbContext(typeof(WorkflowDbContext))]
    partial class WorkflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("workspace")
                .HasAnnotation("ProductVersion", "8.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("workflow.Entities.Review.InfoRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("DueAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<Guid>("RequestedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("requested_by");

                    b.Property<DateTimeOffset?>("RespondedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("responded_at");

                    b.Property<string>("ResponseMessage")
                        .HasColumnType("text")
                        .HasColumnName("response_message");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("OPEN")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("RequestedBy");

                    b.HasIndex("ReviewCaseId", "Status")
                        .HasDatabaseName("ix_info_request_2");

                    b.ToTable("info_request", "review");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid?>("InfoRequestId")
                        .HasColumnType("uuid")
                        .HasColumnName("info_request_id");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UploadedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("uploaded_by");

                    b.HasKey("Id");

                    b.HasIndex("ReviewCaseId")
                        .HasDatabaseName("ix_review_attachment_2");

                    b.HasIndex("UploadedBy");

                    b.HasIndex("ReviewCaseId", "InfoRequestId");

                    b.ToTable("review_attachment", "review");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcceptanceDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acceptance_deadline");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("accepted_at");

                    b.Property<string>("CannotVerifyReason")
                        .HasColumnType("text")
                        .HasColumnName("cannot_verify_reason");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeclineReason")
                        .HasColumnType("text")
                        .HasColumnName("decline_reason");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivered_at");

                    b.Property<DateTimeOffset?>("DeliveryDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_deadline");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("ExpectedOutcome")
                        .HasColumnType("text")
                        .HasColumnName("expected_outcome");

                    b.Property<Guid>("ExpertProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("expert_profile_id");

                    b.Property<long>("Fee")
                        .HasColumnType("bigint")
                        .HasColumnName("fee");

                    b.Property<DateTimeOffset?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<DateTimeOffset?>("PaymentDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("payment_deadline");

                    b.Property<short>("PlatformFeePct")
                        .HasColumnType("smallint")
                        .HasColumnName("platform_fee_pct");

                    b.Property<string>("ProblemDescription")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("problem_description");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("requester_user_id");

                    b.Property<DateTimeOffset>("ResponseDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_deadline");

                    b.Property<string>("Result")
                        .HasColumnType("text")
                        .HasColumnName("result");

                    b.Property<string>("ReviewSummary")
                        .HasColumnType("text")
                        .HasColumnName("review_summary");

                    b.Property<Guid?>("ServiceOfferingId")
                        .HasColumnType("uuid")
                        .HasColumnName("service_offering_id");

                    b.Property<Guid?>("SlotId")
                        .HasColumnType("uuid")
                        .HasColumnName("slot_id");

                    b.Property<Guid>("SourceVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_version_id");

                    b.Property<DateTimeOffset?>("StartDeadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_deadline");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING_EXPERT_RESPONSE")
                        .HasColumnName("status");

                    b.Property<string>("TerminationReason")
                        .HasColumnType("text")
                        .HasColumnName("termination_reason");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ServiceOfferingId");

                    b.HasIndex("SlotId");

                    b.HasIndex("DocumentId", "SourceVersionId");

                    b.HasIndex("ExpertProfileId", "Status")
                        .HasDatabaseName("ix_review_case_4");

                    b.HasIndex("RequesterUserId", "Status")
                        .HasDatabaseName("ix_review_case_6");

                    b.ToTable("review_case", "review");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewStatusHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("FromStatus")
                        .HasColumnType("text")
                        .HasColumnName("from_status");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("to_status");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("ReviewCaseId", "CreatedAt")
                        .HasDatabaseName("ix_review_status_history_2");

                    b.ToTable("review_status_history", "review");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<Guid>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("PENDING")
                        .HasColumnName("status");

                    b.Property<string>("TaskCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("task_code");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("ReviewCaseId", "TaskCode")
                        .IsUnique();

                    b.ToTable("review_task", "review");
                });

            modelBuilder.Entity("workflow.Entities.Stubs.AvailabilitySlotStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("availability_slot", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("workflow.Entities.Stubs.ExpertProfileStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("expert_profile", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("workflow.Entities.Stubs.ServiceOfferingStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("service_offering", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("workflow.Entities.Stubs.UserStub", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.HasKey("Id");

                    b.ToTable("users", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("workflow.Entities.Workspace.AiQuota", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<int>("Balance")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10)
                        .HasColumnName("balance");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId");

                    b.ToTable("ai_quota", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.AiUsage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("CreditHold")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L)
                        .HasColumnName("credit_hold");

                    b.Property<string>("PaidWith")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("paid_with");

                    b.Property<Guid?>("QuestionId")
                        .HasColumnType("uuid")
                        .HasColumnName("question_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("RESERVED")
                        .HasColumnName("state");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("UserId", "State")
                        .HasDatabaseName("ix_ai_usage_2");

                    b.ToTable("ai_usage", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.ChatMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AnswerStatus")
                        .HasColumnType("text")
                        .HasColumnName("answer_status");

                    b.Property<string>("Citations")
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<Guid>("ConversationId")
                        .HasColumnType("uuid")
                        .HasColumnName("conversation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly?>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("ScopeResult")
                        .HasColumnType("text")
                        .HasColumnName("scope_result");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sender");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId", "CreatedAt")
                        .HasDatabaseName("ix_chat_message_2");

                    b.ToTable("chat_message", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Conversation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "UpdatedAt")
                        .HasDatabaseName("ix_conversation_2");

                    b.ToTable("conversation", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("metadata");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date")
                        .HasColumnName("period_end");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date")
                        .HasColumnName("period_start");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("TEMPLATE")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("VerifiedVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_version_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Id", "VerifiedVersionId");

                    b.HasIndex("OwnerUserId", "Status")
                        .HasDatabaseName("ix_document_2");

                    b.ToTable("document", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.DocumentVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Citations")
                        .HasColumnType("jsonb")
                        .HasColumnName("citations");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("content");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<string>("DraftAssessment")
                        .HasColumnType("text")
                        .HasColumnName("draft_assessment");

                    b.Property<string>("FileUrl")
                        .HasColumnType("text")
                        .HasColumnName("file_url");

                    b.Property<Guid?>("InputSnapshotId")
                        .HasColumnType("uuid")
                        .HasColumnName("input_snapshot_id");

                    b.Property<bool>("IsImmutable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_immutable");

                    b.Property<Guid?>("ReviewCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_case_id");

                    b.Property<Guid?>("TemplateVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_version_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.Property<string>("VersionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("version_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ReviewCaseId")
                        .HasDatabaseName("ix_document_version_6");

                    b.HasIndex("TemplateVersionId");

                    b.HasIndex("DocumentId", "InputSnapshotId");

                    b.HasIndex("DocumentId", "ReviewCaseId");

                    b.HasIndex("DocumentId", "VersionNo")
                        .IsUnique();

                    b.ToTable("document_version", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.InputSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("document_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("DocumentId", "VersionNo")
                        .IsUnique();

                    b.ToTable("input_snapshot", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("template", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.TemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("FieldSchema")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("field_schema");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("DRAFT")
                        .HasColumnName("status");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TemplateId", "VersionNo")
                        .IsUnique();

                    b.ToTable("template_version", "workspace");
                });

            modelBuilder.Entity("workflow.Entities.Review.InfoRequest", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("RequestedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_info_request_50");

                    b.HasOne("workflow.Entities.Review.ReviewCase", "ReviewCase")
                        .WithMany("InfoRequests")
                        .HasForeignKey("ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_info_request_49");

                    b.Navigation("ReviewCase");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewAttachment", b =>
                {
                    b.HasOne("workflow.Entities.Review.ReviewCase", "ReviewCase")
                        .WithMany("Attachments")
                        .HasForeignKey("ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_attachment_51");

                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UploadedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_attachment_52");

                    b.HasOne("workflow.Entities.Review.InfoRequest", "InfoRequest")
                        .WithMany("Attachments")
                        .HasForeignKey("ReviewCaseId", "InfoRequestId")
                        .HasPrincipalKey("ReviewCaseId", "Id")
                        .HasConstraintName("fk_review_attachment_53");

                    b.Navigation("InfoRequest");

                    b.Navigation("ReviewCase");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewCase", b =>
                {
                    b.HasOne("workflow.Entities.Workspace.Document", null)
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_case_42");

                    b.HasOne("workflow.Entities.Stubs.ExpertProfileStub", null)
                        .WithMany()
                        .HasForeignKey("ExpertProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_case_44");

                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_case_43");

                    b.HasOne("workflow.Entities.Stubs.ServiceOfferingStub", null)
                        .WithMany()
                        .HasForeignKey("ServiceOfferingId")
                        .HasConstraintName("fk_review_case_46");

                    b.HasOne("workflow.Entities.Stubs.AvailabilitySlotStub", null)
                        .WithMany()
                        .HasForeignKey("SlotId")
                        .HasConstraintName("fk_review_case_45");

                    b.HasOne("workflow.Entities.Workspace.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "SourceVersionId")
                        .HasPrincipalKey("DocumentId", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_case_47");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewStatusHistory", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .HasConstraintName("fk_review_status_history_55");

                    b.HasOne("workflow.Entities.Review.ReviewCase", "ReviewCase")
                        .WithMany("StatusHistories")
                        .HasForeignKey("ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_status_history_54");

                    b.Navigation("ReviewCase");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewTask", b =>
                {
                    b.HasOne("workflow.Entities.Review.ReviewCase", "ReviewCase")
                        .WithMany("ReviewTasks")
                        .HasForeignKey("ReviewCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_task_48");

                    b.Navigation("ReviewCase");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.AiQuota", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_quota_28");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.AiUsage", b =>
                {
                    b.HasOne("workflow.Entities.Workspace.Conversation", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId")
                        .HasConstraintName("fk_ai_usage_30");

                    b.HasOne("workflow.Entities.Workspace.ChatMessage", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .HasConstraintName("fk_ai_usage_31");

                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ai_usage_29");

                    b.Navigation("Conversation");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.ChatMessage", b =>
                {
                    b.HasOne("workflow.Entities.Workspace.Conversation", "Conversation")
                        .WithMany("Messages")
                        .HasForeignKey("ConversationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chat_message_27");

                    b.Navigation("Conversation");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Conversation", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_conversation_26");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Document", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_32");

                    b.HasOne("workflow.Entities.Workspace.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .HasConstraintName("fk_document_33");

                    b.HasOne("workflow.Entities.Workspace.DocumentVersion", null)
                        .WithMany()
                        .HasForeignKey("Id", "VerifiedVersionId")
                        .HasPrincipalKey("DocumentId", "Id")
                        .HasConstraintName("fk_document_40");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.DocumentVersion", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_version_37");

                    b.HasOne("workflow.Entities.Workspace.Document", "Document")
                        .WithMany("Versions")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_document_version_36");

                    b.HasOne("workflow.Entities.Workspace.TemplateVersion", "TemplateVersion")
                        .WithMany()
                        .HasForeignKey("TemplateVersionId")
                        .HasConstraintName("fk_document_version_38");

                    b.HasOne("workflow.Entities.Workspace.InputSnapshot", "InputSnapshot")
                        .WithMany()
                        .HasForeignKey("DocumentId", "InputSnapshotId")
                        .HasPrincipalKey("DocumentId", "Id")
                        .HasConstraintName("fk_document_version_39");

                    b.HasOne("workflow.Entities.Review.ReviewCase", null)
                        .WithMany()
                        .HasForeignKey("DocumentId", "ReviewCaseId")
                        .HasPrincipalKey("DocumentId", "Id")
                        .HasConstraintName("fk_document_version_41");

                    b.Navigation("Document");

                    b.Navigation("InputSnapshot");

                    b.Navigation("TemplateVersion");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.InputSnapshot", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_input_snapshot_35");

                    b.HasOne("workflow.Entities.Workspace.Document", "Document")
                        .WithMany("InputSnapshots")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_input_snapshot_34");

                    b.Navigation("Document");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.TemplateVersion", b =>
                {
                    b.HasOne("workflow.Entities.Stubs.UserStub", null)
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_version_25");

                    b.HasOne("workflow.Entities.Workspace.Template", "Template")
                        .WithMany("Versions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_template_version_24");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("workflow.Entities.Review.InfoRequest", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("workflow.Entities.Review.ReviewCase", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("InfoRequests");

                    b.Navigation("ReviewTasks");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Conversation", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Document", b =>
                {
                    b.Navigation("InputSnapshots");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("workflow.Entities.Workspace.Template", b =>
                {
                    b.Navigation("Versions");
                });
#pragma warning restore 612, 618
        }
    }
}
